name: NPM Package
on:
  workflow_call:
    inputs:
      workflow-ref:
        required: true
        type: string
        description: "The workflow ref."
      package:
        required: true
        type: string
        description: "The path to the package within the local repo."
      publish-gpr:
        required: false
        default: false
        type: boolean
        description: "Should the package be published to the GitHub Package Registry?"
      replace-version:
        required: false
        type: string
        description: "If provided, the package version will be overwritten."
      cache-key:
        required: false
        type: string
        description: "If provided, a cache with this key will be used."

jobs:
  test:
    runs-on: ubuntu-latest
    name: "Test"

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Dependencies
        uses: actions/cache@v3
        if: ${{ inputs.cache-key != '' }}
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ inputs.cache-key }}-${{ hashFiles('${{ inputs.package }}/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ inputs.cache-key }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Dependencies
        run: |
          cd "${{ inputs.package }}"
          npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Tests
        run: |
          cd "${{ inputs.package }}"
          npm test

  # Publish to GitHub Package Registry
  publish-gpr:
    runs-on: ubuntu-latest
    needs: test
    name: "Publish to GitHub Packages"
    if: ${{ inputs.publish-gpr }}

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout Helpers
        uses: actions/checkout@v3
        with:
          repository: 'sfusurge/actions-workflows'
          ref: "${{ inputs.workflow-ref }}"
          path: ".surge-workflows"

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          registry-url: 'https://npm.pkg.github.com'
          scope: 'sfusurge'

      - name: Cache Dependencies
        uses: actions/cache@v3
        if: ${{ inputs.cache-key != '' }}
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ inputs.cache-key }}-${{ hashFiles('${{ inputs.package }}/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ inputs.cache-key }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - uses: ./.surge-workflows/.github/actions/npm-rewrite-package-version
        if: ${{ inputs.replace-version != '' }}
        with:
          package: "${{ inputs.package }}"
          replace-version: "${{ inputs.replace-version }}"

      - name: Publish Package
        shell: bash
        run: |
          cd "${{ inputs.package }}"
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
